# This is a basic workflow to help you get started with Actions

name: deploy-yoman

on:
  push:
    branches: [ "main" ]

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAYYBWEZ2FSTYI4ZF6
          aws-secret-access-key: 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
          aws-region: eu-central-1

      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      - name: Install dependencies
        run: npm install   
      - name: Generate build
        run: npm run build
        env:
         CI: false
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
      - name: Deploy app build to S3 bucket
        run: aws s3 sync build s3://yoman.4sport-live.com
      - name: disable index.html cache
        run: aws s3 cp s3://yoman.4sport-live.com/index.html s3://yoman.4sport-live.com/index.html --metadata-directive REPLACE --cache-control max-age=0 --content-type "text/html"
